/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ErdalBankYoneticiPaneli;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class YöneticiMüsteriEkleme extends javax.swing.JFrame {

    /**
     * Creates new form YöneticiMüsteriEkleme
     */
    public YöneticiMüsteriEkleme() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel9 = new javax.swing.JLabel();
        müsteriAdi = new javax.swing.JTextField();
        müsteriSoyadi = new javax.swing.JTextField();
        kimlikNo = new javax.swing.JTextField();
        müsteriHesapNo = new javax.swing.JTextField();
        müsteriHesapParolası = new javax.swing.JTextField();
        müsteriDogumYeri = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setText("Geri Dön");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 152, 42));

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setText("Müşteri Kaydı Tamamla");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(371, 180, 190, 42));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ekranı Temizle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 170, 42));

        jButton4.setBackground(new java.awt.Color(255, 204, 204));
        jButton4.setText("Kayıtlı Müşteriler");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 136, 41));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 680, 156));

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 102));
        jLabel9.setText("Not: Müşteri Eklerken Kisisel Bilgiler'de Türkçe karakter kullanılmayacaktır");
        jDesktopPane1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        müsteriAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                müsteriAdiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                müsteriAdiKeyReleased(evt);
            }
        });
        jDesktopPane1.add(müsteriAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 139, -1));

        müsteriSoyadi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                müsteriSoyadiKeyReleased(evt);
            }
        });
        jDesktopPane1.add(müsteriSoyadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 139, -1));

        kimlikNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kimlikNoKeyReleased(evt);
            }
        });
        jDesktopPane1.add(kimlikNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 139, -1));

        müsteriHesapNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                müsteriHesapNoKeyReleased(evt);
            }
        });
        jDesktopPane1.add(müsteriHesapNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 147, -1));
        jDesktopPane1.add(müsteriHesapParolası, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 147, -1));

        müsteriDogumYeri.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                müsteriDogumYeriKeyReleased(evt);
            }
        });
        jDesktopPane1.add(müsteriDogumYeri, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 147, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Müşteri Hesap No :");
        jDesktopPane1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Müşteri Hesap Parolası :");
        jDesktopPane1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Müşteri Doğum Yeri:");
        jDesktopPane1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Müşteri Kimlik No ( TC ) :");
        jDesktopPane1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Müşterinin Soyadı :");
        jDesktopPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Müşterinin Adı :");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ERDAL BANK MÜŞTERİ EKLEME PANELİ");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            YöneticiAnaSayfa anesne = new YöneticiAnaSayfa();
            anesne.setVisible(true);
            this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      müsteriAdi.setText(" ");
      müsteriSoyadi.setText(" ");
      müsteriHesapNo.setText(" ");
      müsteriHesapParolası.setText(" ");
      müsteriDogumYeri.setText(" ");
      kimlikNo.setText(" ");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String ad=String.valueOf(müsteriAdi.getText());
        String soyad=String.valueOf(müsteriSoyadi.getText());
        String kAdi=String.valueOf(kimlikNo.getText());
        String hesapNo=String.valueOf(müsteriHesapNo.getText());
        String hesapParola=String.valueOf(müsteriHesapParolası.getText());
        String DogumYeri=String.valueOf(müsteriDogumYeri.getText());
       char sinir[]=kAdi.toCharArray();
       char sinir1[]=hesapNo.toCharArray();
       
            if(sinir.length==11 && sinir1.length==8){
                
             
            
            
        
        
        try 
        { 
            
        
            Class.forName("com.mysql.jdbc.Driver");
            
            String baglantiYolu="jdbc:mysql://localhost:3306/projeveritabani";
            String kullaniciAdi="root";
            String parola="";
            
            System.out.println("Buraya Kadar sorunsuz çalıştı 1");
            /* Bağlantı nesnesi oluşturuldu*/
            Connection bn=DriverManager.getConnection(baglantiYolu,kullaniciAdi,parola);
        
             
            
        
           System.out.println("Buraya Kadar sorunsuz çalıştı 2");
          
            String sorgu="INSERT INTO musterikayit(musteriAdi,musteriSoyadi,musteriKimlikNo,musteriDogumYeri,musteriHesapNo,musteriHesapParola) VALUES(?,?,?,?,?,?)";
            PreparedStatement   PreparedStatementNesnesi=bn.prepareStatement(sorgu);
            PreparedStatementNesnesi.setString(1, ad);
            PreparedStatementNesnesi.setString(2, soyad);
            PreparedStatementNesnesi.setString(3, kAdi);
            PreparedStatementNesnesi.setString(4, DogumYeri);
            PreparedStatementNesnesi.setString(5, hesapNo );
            PreparedStatementNesnesi.setString(6, hesapParola);
            System.out.println("Buraya Kadar sorunsuz çalıştı 3");
            int islemSonucu=PreparedStatementNesnesi.executeUpdate();
            System.out.println("Buraya Kadar sorunsuz çalıştı 4");
            
            
            if(islemSonucu>0)
            {
                JOptionPane.showMessageDialog(null, "Müşteri Kaydı Tamamlandı.");
                /*Bu kısma veri eklendikten sonra textfieldleri sıfırlamak için kod yazabilirsin*/
            }else
            {
                 JOptionPane.showMessageDialog(null, " ");
            }
           
            
        }
        catch (Exception e)
        {    
              JOptionPane.showMessageDialog(null, "Lütfen TC no ,Hesap Numarası ve Hesap Parolasını boş bırakmayınız. Eğer boş bırakmadıysanız.\nDaha önceden bu TC veya Hesap Numarasına ait kayıt bulunmaktadır.");
        }}else{JOptionPane.showMessageDialog(null, "Lütfen TC no ,Hesap numaranızı kontrol ediniz.");}       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        try {
        Class.forName("com.mysql.jdbc.Driver");
         String baglantiYolu="jdbc:mysql://localhost:3306/projeveritabani";
         String kullaniciAdi="root";
         String parola="";
        System.out.println("Buraya Kadar sorunsuz çalıştı 1");
       Connection bnNesne=DriverManager.getConnection(baglantiYolu,kullaniciAdi,parola);
        
        
        System.out.println("Buraya Kadar sorunsuz çalıştı 2");
        Statement st = (Statement) bnNesne.createStatement();
        System.out.println("Buraya Kadar sorunsuz çalıştı 3");
        try (ResultSet rs = st.executeQuery("Select * from musterikayit")) { //Veritabanındaki tabloya bağlandık
            int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
            DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
            for(int i = 1;i<=colcount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i)); 
System.out.println("Buraya Kadar sorunsuz çalıştı 4");//Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);
                    tm.addRow(row);
                }
            jTable1.setModel(tm);
        }
        bnNesne.close();
    } catch (ClassNotFoundException | SQLException hata) {
       ;
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void müsteriAdiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_müsteriAdiKeyReleased
        // TODO add your handling code here:
         
             
                char dizi[]=String.valueOf(müsteriAdi.getText().trim()).toCharArray();
                char harf[]=new char[1];
               for(int i=0;i<dizi.length;i++)
               {
                   
                   harf[0] =dizi[i];
                   String kelime=new String(harf);
                   
                   if(kelime.equals("0") || kelime.equals("1") || kelime.equals("2") || kelime.equals("3") || kelime.equals("4") || kelime.equals("5") || kelime.equals("6") || kelime.equals("7") || kelime.equals("8") || kelime.equals("9"))
                   {
                       JOptionPane.showMessageDialog(null, " Lütfen rakam girmeyiniz.");
                       müsteriAdi.setText(" ");
                   }
                   
               }
        
            
    }//GEN-LAST:event_müsteriAdiKeyReleased

    private void müsteriAdiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_müsteriAdiKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_müsteriAdiKeyPressed

    private void müsteriHesapNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_müsteriHesapNoKeyReleased
        // TODO add your handling code here: 
        
                char dizi[]=String.valueOf(müsteriHesapNo.getText().trim()).toCharArray();
                char harf[]=new char[1];
               for(int i=0;i<dizi.length;i++)
               {
                   
                   harf[0] =dizi[i];
                   String kelime=new String(harf);
                  try
                  {
                       int rakam =Integer.valueOf(kelime);
                  }
                  catch(Exception  e)
                  {
                       JOptionPane.showMessageDialog(null, " Lütfen harf girmeyiniz.");
                        müsteriHesapNo.setText("");
                  }
      
                  
                   
                   
               }
    }//GEN-LAST:event_müsteriHesapNoKeyReleased

    private void müsteriSoyadiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_müsteriSoyadiKeyReleased
 char dizi[]=String.valueOf(müsteriSoyadi.getText().trim()).toCharArray();
                char harf[]=new char[1];
               for(int i=0;i<dizi.length;i++)
               {
                   
                   harf[0] =dizi[i];
                   String kelime=new String(harf);
                   
                   if(kelime.equals("0") || kelime.equals("1") || kelime.equals("2") || kelime.equals("3") || kelime.equals("4") || kelime.equals("5") || kelime.equals("6") || kelime.equals("7") || kelime.equals("8") || kelime.equals("9"))
                   {
                       JOptionPane.showMessageDialog(null, " Lütfen rakam girmeyiniz.");
                       müsteriSoyadi.setText(" ");
                   }
                   
               }



        // TODO add your handling code here:
    }//GEN-LAST:event_müsteriSoyadiKeyReleased

    private void kimlikNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kimlikNoKeyReleased
 
        
        char dizi[]=String.valueOf(kimlikNo.getText().trim()).toCharArray();
                char harf[]=new char[1];
               for(int i=0;i<dizi.length;i++)
               {
                   
                   harf[0] =dizi[i];
                   String kelime=new String(harf);
                  try
                  {
                       int rakam =Integer.valueOf(kelime);
                  }
                  catch(Exception  e)
                  {
                       JOptionPane.showMessageDialog(null, " Lütfen harf girmeyiniz.");
                        kimlikNo.setText("");
                  }
      
                  
                   
                   
               }
                



        // TODO add your handling code here:
    }//GEN-LAST:event_kimlikNoKeyReleased

    private void müsteriDogumYeriKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_müsteriDogumYeriKeyReleased

 char dizi[]=String.valueOf(müsteriDogumYeri.getText().trim()).toCharArray();
                char harf[]=new char[1];
               for(int i=0;i<dizi.length;i++)
               {
                   
                   harf[0] =dizi[i];
                   String kelime=new String(harf);
                   
                   if(kelime.equals("0") || kelime.equals("1") || kelime.equals("2") || kelime.equals("3") || kelime.equals("4") || kelime.equals("5") || kelime.equals("6") || kelime.equals("7") || kelime.equals("8") || kelime.equals("9"))
                   {
                       JOptionPane.showMessageDialog(null, " Lütfen rakam girmeyiniz.");
                       müsteriDogumYeri.setText(" ");
                   }
                   
               }

        // TODO add your handling code here:
    }//GEN-LAST:event_müsteriDogumYeriKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YöneticiMüsteriEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YöneticiMüsteriEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YöneticiMüsteriEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YöneticiMüsteriEkleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YöneticiMüsteriEkleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kimlikNo;
    private javax.swing.JTextField müsteriAdi;
    private javax.swing.JTextField müsteriDogumYeri;
    private javax.swing.JTextField müsteriHesapNo;
    private javax.swing.JTextField müsteriHesapParolası;
    private javax.swing.JTextField müsteriSoyadi;
    // End of variables declaration//GEN-END:variables
}
