/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ErdalBankYoneticiPaneli;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class YöneticiMüsteriGüncelle extends javax.swing.JFrame {

    /**
     * Creates new form YöneticiMüsteriGüncelle
     */
    public YöneticiMüsteriGüncelle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        müsteriHesapParolasıgüncel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        müsteriDogumYerigüncel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        müsteriAdigüncel = new javax.swing.JTextField();
        müsteriSoyadigüncel = new javax.swing.JTextField();
        kimlikNogüncel = new javax.swing.JTextField();
        musteriHesapNogüncel = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        GüncelMüsteri = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("ERDAL BANK MÜŞTERİ GÜNCELLEME PANELİ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 19, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Müşterinin Adı :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 106, -1, -1));
        getContentPane().add(müsteriHesapParolasıgüncel, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 135, 147, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Müşterinin Soyadı :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 137, -1, -1));
        getContentPane().add(müsteriDogumYerigüncel, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 166, 139, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Müşteri Kimlik No ( TC ) :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 66, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Müşteri Hesap No :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 106, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Müşteri Hesap Parolası :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 137, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Müşteri Doğum Yeri:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 168, -1, -1));

        müsteriAdigüncel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                müsteriAdigüncelKeyReleased(evt);
            }
        });
        getContentPane().add(müsteriAdigüncel, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 104, 139, -1));

        müsteriSoyadigüncel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                müsteriSoyadigüncelKeyReleased(evt);
            }
        });
        getContentPane().add(müsteriSoyadigüncel, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 135, 139, -1));

        kimlikNogüncel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kimlikNogüncelActionPerformed(evt);
            }
        });
        kimlikNogüncel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kimlikNogüncelKeyReleased(evt);
            }
        });
        getContentPane().add(kimlikNogüncel, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 64, 231, -1));

        musteriHesapNogüncel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                musteriHesapNogüncelKeyReleased(evt);
            }
        });
        getContentPane().add(musteriHesapNogüncel, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 104, 147, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setText("Ekranı Temizle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 231, 170, 39));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setText("Geri Dön");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 231, 192, 39));

        jButton3.setBackground(new java.awt.Color(255, 255, 204));
        jButton3.setText("Müşteriyi Güncelle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 231, 173, 39));

        GüncelMüsteri.setBackground(new java.awt.Color(255, 255, 204));
        GüncelMüsteri.setText("Müşteriyi Bul");
        GüncelMüsteri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GüncelMüsteriActionPerformed(evt);
            }
        });
        getContentPane().add(GüncelMüsteri, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 63, 168, -1));

        jScrollPane1.setViewportView(jTable1);

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(297, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            YöneticiAnaSayfa enesne = new YöneticiAnaSayfa();
            enesne.setVisible(true);
            this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        String ad=String.valueOf(müsteriAdigüncel.getText());
        String soyad=String.valueOf(müsteriSoyadigüncel.getText());
        String hesapNo=String.valueOf(musteriHesapNogüncel.getText());
        String hesapParola=String.valueOf(müsteriHesapParolasıgüncel.getText());
        String DogumYeri=String.valueOf(müsteriDogumYerigüncel.getText());
        try 
        { 
            Class.forName("com.mysql.jdbc.Driver");
        
            /*Değişkenleri tanımladık*/
            String baglantiYolu="jdbc:mysql://localhost:3306/projeveritabani";
            String kullaniciAdi="root";
            String parola="";
            
            System.out.println("Buraya Kadar sorunsuz çalıştı 1");
            /* Bağlantı nesnesi oluşturuldu*/
            Connection bn=DriverManager.getConnection(baglantiYolu,kullaniciAdi,parola);
        
             
            
        
            System.out.println("Buraya Kadar sorunsuz çalıştı 2");
           String guncellemeSorgusu="UPDATE musterikayit set "
                                        + "musteriAdi=?,"
                                        + "musteriSoyadi=?,"
                                        + "musteriDogumYeri=?,"
                                        + "musteriHesapNo=?,"
                                        + "musteriHesapParola=?"
                                        + " WHERE musteriKimlikNo=?"; 
            PreparedStatement   PreparedStatementNesnesi=bn.prepareStatement(guncellemeSorgusu);
            PreparedStatementNesnesi.setString(1, ad);
            PreparedStatementNesnesi.setString(2, soyad);
            PreparedStatementNesnesi.setString(3, DogumYeri);
            PreparedStatementNesnesi.setString(4, hesapNo );
            PreparedStatementNesnesi.setString(5, hesapParola);
            PreparedStatementNesnesi.setString(6,String.valueOf( kimlikNogüncel.getText())); 
            System.out.println("Buraya Kadar sorunsuz çalıştı 3");
            int islemSonucu=PreparedStatementNesnesi.executeUpdate();
            System.out.println("Buraya Kadar sorunsuz çalıştı 4");
            if(islemSonucu>0)
            {
                JOptionPane.showMessageDialog(null, "Müşteri Güncellendi");
                /*Bu kısma veri eklendikten sonra textfieldleri sıfırlamak için kod yazabilirsin*/
            }else
            {
                 JOptionPane.showMessageDialog(null, "Lütfen TC ve Hesap Numarası ve Hesap Parolasını boş bırakmayınız.");
            }
           
            
        }
        catch (Exception e)
        {    
              JOptionPane.showMessageDialog(null, "Kontrol sağlayınız. Tekrar Deneyiniz.");
        }    
        
        try {
        Class.forName("com.mysql.jdbc.Driver");
         String baglantiYolu="jdbc:mysql://localhost:3306/projeveritabani";
         String kullaniciAdi="root";
         String parola="";
        System.out.println("Buraya Kadar sorunsuz çalıştı 1");
       Connection bnNesne=DriverManager.getConnection(baglantiYolu,kullaniciAdi,parola);
        
        
        System.out.println("Buraya Kadar sorunsuz çalıştı 2");
        Statement st = (Statement) bnNesne.createStatement();
        System.out.println("Buraya Kadar sorunsuz çalıştı 3");
        try (ResultSet rs = st.executeQuery("Select * from musterikayit")) { //Veritabanındaki tabloya bağlandık
            int colcount = rs.getMetaData().getColumnCount(); //Veritabanındaki tabloda kaç tane sütun var?
            DefaultTableModel tm = new DefaultTableModel(); //Model oluşturuyoruz
            for(int i = 1;i<=colcount;i++)
                tm.addColumn(rs.getMetaData().getColumnName(i)); 
System.out.println("Buraya Kadar sorunsuz çalıştı 4");//Tabloya sütun ekliyoruz veritabanımızdaki sütun ismiyle aynı olacak şekilde
            while(rs.next())
                {
                    Object[] row = new Object[colcount];
                    for(int i=1;i<=colcount;i++)
                        row[i-1] = rs.getObject(i);
                    tm.addRow(row);
                }
            jTable1.setModel(tm);
        }
        bnNesne.close();
    } catch (ClassNotFoundException | SQLException hata) {
       ;
    }
        
        
        
        
        
        
        
       
    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        müsteriAdigüncel.setText(" ");
      müsteriSoyadigüncel.setText(" ");
      musteriHesapNogüncel.setText(" ");
      müsteriHesapParolasıgüncel.setText(" ");
      müsteriDogumYerigüncel.setText(" ");
      kimlikNogüncel.setText(" ");   // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GüncelMüsteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GüncelMüsteriActionPerformed

 try{
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/projeveritabani","root","");
      Statement std=(Statement) con.createStatement();
      String kAdi=String.valueOf(kimlikNogüncel.getText());
        System.out.println("Buraya Kadar sorunsuz çalıştı 2");
      String SQL ="SELECT * FROM musterikayit WHERE musteriKimlikNo='"+kAdi+"'";
      ResultSet rs =std.executeQuery(SQL);
      System.out.println("Buraya Kadar sorunsuz çalıştı 3");
      while(rs.next()){
         müsteriAdigüncel.setText(""+rs.getString("musteriAdi"));
         müsteriSoyadigüncel.setText(""+rs.getString("musteriSoyadi"));
         musteriHesapNogüncel.setText(""+rs.getString("musteriHesapNo"));
         müsteriHesapParolasıgüncel.setText(""+rs.getString("musteriHesapParola"));
         müsteriDogumYerigüncel.setText(""+rs.getString("musteriDogumYeri"));
         
      
      }
      
      
      
      }catch(Exception e){}



        // TODO add your handling code here:
    }//GEN-LAST:event_GüncelMüsteriActionPerformed

    private void kimlikNogüncelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kimlikNogüncelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kimlikNogüncelActionPerformed

    private void müsteriAdigüncelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_müsteriAdigüncelKeyReleased

  char dizi[]=String.valueOf(müsteriAdigüncel.getText().trim()).toCharArray();
                char harf[]=new char[1];
               for(int i=0;i<dizi.length;i++)
               {
                   
                   harf[0] =dizi[i];
                   String kelime=new String(harf);
                   
                   if(kelime.equals("0") || kelime.equals("1") || kelime.equals("2") || kelime.equals("3") || kelime.equals("4") || kelime.equals("5") || kelime.equals("6") || kelime.equals("7") || kelime.equals("8") || kelime.equals("9"))
                   {
                       JOptionPane.showMessageDialog(null, " Lütfen rakam girmeyiniz.");
                       müsteriAdigüncel.setText(" ");
                   }
                   
               }


        // TODO add your handling code here:
    }//GEN-LAST:event_müsteriAdigüncelKeyReleased

    private void müsteriSoyadigüncelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_müsteriSoyadigüncelKeyReleased

          char dizi[]=String.valueOf(müsteriSoyadigüncel.getText().trim()).toCharArray();
                char harf[]=new char[1];
               for(int i=0;i<dizi.length;i++)
               {
                   
                   harf[0] =dizi[i];
                   String kelime=new String(harf);
                   
                   if(kelime.equals("0") || kelime.equals("1") || kelime.equals("2") || kelime.equals("3") || kelime.equals("4") || kelime.equals("5") || kelime.equals("6") || kelime.equals("7") || kelime.equals("8") || kelime.equals("9"))
                   {
                       JOptionPane.showMessageDialog(null, " Lütfen rakam girmeyiniz.");
                       müsteriSoyadigüncel.setText(" ");
                   }
                   
               }


        // TODO add your handling code here:
    }//GEN-LAST:event_müsteriSoyadigüncelKeyReleased

    private void kimlikNogüncelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kimlikNogüncelKeyReleased
 char dizi[]=String.valueOf(kimlikNogüncel.getText().trim()).toCharArray();
                char harf[]=new char[1];
               for(int i=0;i<dizi.length;i++)
               {
                   
                   harf[0] =dizi[i];
                   String kelime=new String(harf);
                  try
                  {
                       int rakam =Integer.valueOf(kelime);
                  }
                  catch(Exception  e)
                  {
                       JOptionPane.showMessageDialog(null, " Lütfen harf girmeyiniz.");
                        kimlikNogüncel.setText("");
                  }
      
                  
                   
                   
               }


        // TODO add your handling code here:
    }//GEN-LAST:event_kimlikNogüncelKeyReleased

    private void musteriHesapNogüncelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_musteriHesapNogüncelKeyReleased

char dizi[]=String.valueOf(musteriHesapNogüncel.getText().trim()).toCharArray();
                char harf[]=new char[1];
               for(int i=0;i<dizi.length;i++)
               {
                   
                   harf[0] =dizi[i];
                   String kelime=new String(harf);
                  try
                  {
                       int rakam =Integer.valueOf(kelime);
                  }
                  catch(Exception  e)
                  {
                       JOptionPane.showMessageDialog(null, " Lütfen harf girmeyiniz.");
                        musteriHesapNogüncel.setText("");
                  }
      
                  
                   
                   
               }

        // TODO add your handling code here:
    }//GEN-LAST:event_musteriHesapNogüncelKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YöneticiMüsteriGüncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YöneticiMüsteriGüncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YöneticiMüsteriGüncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YöneticiMüsteriGüncelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YöneticiMüsteriGüncelle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GüncelMüsteri;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kimlikNogüncel;
    private javax.swing.JTextField musteriHesapNogüncel;
    private javax.swing.JTextField müsteriAdigüncel;
    private javax.swing.JTextField müsteriDogumYerigüncel;
    private javax.swing.JTextField müsteriHesapParolasıgüncel;
    private javax.swing.JTextField müsteriSoyadigüncel;
    // End of variables declaration//GEN-END:variables
}
