/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ErdalBankYoneticiPaneli;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class YöneticiKısaVadeliHesapAcma extends javax.swing.JFrame {

    /**
     * Creates new form YöneticiKısaVadeliHesapAcma
     */
    public YöneticiKısaVadeliHesapAcma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        a = new javax.swing.JTextField();
        s = new javax.swing.JTextField();
        h = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        k = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tcc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ERDAL BANK KISA VADELİ HESAP AÇMA PANELİ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Müşterinin Adı :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Müşterinin Soyadı :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Müşteri Hesap No :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 120, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Müşteri Hesap Parolasi :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 155, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Müşteri Kimlik No :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 191, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Başlangıç Bakiyesi :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 222, -1, -1));
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 57, 146, -1));
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 90, 146, -1));
        getContentPane().add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 122, 146, -1));
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 156, 146, -1));
        getContentPane().add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 189, 146, -1));
        getContentPane().add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 220, 146, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tc Kimlik No ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));
        getContentPane().add(tcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 161, -1));

        jButton1.setText("Bilgileri Getir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 121, 161, -1));

        jButton2.setText("Geri");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 155, -1, -1));

        jButton3.setText("Hesap Aç");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 155, 100, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

try{
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/projeveritabani","root","");
      Statement std=(Statement) con.createStatement();
      String kAdi=String.valueOf(tcc.getText());
       System.out.println("Buraya Kadar sorunsuz çalıştı 2");
      String SQL ="SELECT * FROM musterikayit WHERE musteriKimlikNo='"+kAdi+"'";
      ResultSet rs =std.executeQuery(SQL);
      System.out.println("Buraya Kadar sorunsuz çalıştı 3");
      while(rs.next()){
         a.setText(""+rs.getString("musteriAdi"));
         s.setText(""+rs.getString("musteriSoyadi"));
         h.setText(""+rs.getString("musteriHesapNo"));
         p.setText(""+rs.getString("musteriHesapParola"));
         k.setText(""+rs.getString("musteriKimlikNo"));
         
      
      }System.out.println("Buraya Kadar sorunsuz çalıştı 3");
      
      
      
      }catch(Exception e){}





        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        YöneticiHesapİslemleri s =new YöneticiHesapİslemleri();
        s.setVisible(true);
        this.setVisible(false);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        String ad=String.valueOf(a.getText());
        String soyad=String.valueOf(s.getText());
        String tc=String.valueOf(k.getText());
        String hesapNo=String.valueOf(h.getText());
        String hesapParola=String.valueOf(p.getText());
        String Bakiye=String.valueOf(b.getText());
        try 
        { 
            Class.forName("com.mysql.jdbc.Driver");
            
            String baglantiYolu="jdbc:mysql://localhost:3306/projeveritabani";
            String kullaniciAdi="root";
            String parola="";
            
            System.out.println("Buraya Kadar sorunsuz çalıştı 1");
            /* Bağlantı nesnesi oluşturuldu*/
            Connection bn=DriverManager.getConnection(baglantiYolu,kullaniciAdi,parola);
        
             
            
        
           System.out.println("Buraya Kadar sorunsuz çalıştı 2");
          
            String sorgu="INSERT INTO kisavadelihesapkayit(kisaVadeliMusteriAd,kisaVadeliMusteriSoyad,kisaVadeliMusteriHesapNo,kisaVadeliMusteriHesapParola,kisaVadeliMusteriTcNo,kisaVadeliMusteriBakiye) VALUES(?,?,?,?,?,?)";
            PreparedStatement   PreparedStatementNesnesi=bn.prepareStatement(sorgu);
            PreparedStatementNesnesi.setString(1, ad);
            PreparedStatementNesnesi.setString(2, soyad);
            PreparedStatementNesnesi.setString(3, hesapNo);
            PreparedStatementNesnesi.setString(4, hesapParola);
            PreparedStatementNesnesi.setString(5, tc );
            PreparedStatementNesnesi.setString(6, Bakiye);
            System.out.println("Buraya Kadar sorunsuz çalıştı 3");
            int islemSonucu=PreparedStatementNesnesi.executeUpdate();
            System.out.println("Buraya Kadar sorunsuz çalıştı 4");
            if(islemSonucu>0)
            {
                JOptionPane.showMessageDialog(null, "Kısa Vadeli Hesap Eklendi");
             
            }else
            {
                 JOptionPane.showMessageDialog(null, " ");
            }
           
            
        }
        catch (Exception e)
        {    
              JOptionPane.showMessageDialog(null, "Vadeli Hesap Kayit Edilmedi");
        }    










        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YöneticiKısaVadeliHesapAcma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YöneticiKısaVadeliHesapAcma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YöneticiKısaVadeliHesapAcma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YöneticiKısaVadeliHesapAcma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YöneticiKısaVadeliHesapAcma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField b;
    private javax.swing.JTextField h;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField k;
    private javax.swing.JTextField p;
    private javax.swing.JTextField s;
    private javax.swing.JTextField tcc;
    // End of variables declaration//GEN-END:variables
}
