/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ErdalBankKullanıcıPaneli;

import ErdalBankYoneticiPaneli.araBellek;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class HesapKilitlemeTalebi extends javax.swing.JFrame {
Socket socket;
          ObjectOutputStream cikisNesne;
          ObjectInputStream girisNesne;
    /**
     * Creates new form HesapKilitlemeTalebi
     */
    public HesapKilitlemeTalebi() {
        initComponents();
    }public void yukle(Socket socket, ObjectOutputStream cikisNesne,ObjectInputStream girisNesne){
        this.socket=socket;
        this.cikisNesne=cikisNesne;
        this.girisNesne=girisNesne;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        asss = new javax.swing.JTextField();
        saaaa = new javax.swing.JTextField();
        kkkk = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("ERDAL BANK HESAP KİLİTLEME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 11, 241, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("RANDEVU SİSTEMİ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 34, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Adınız :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 86, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Soyadınız :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 117, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TC Kimlik :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 148, -1, -1));

        jButton1.setText("Geri Dön");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 190, 96, 31));

        jButton2.setText("Bilgilerimi Getir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 190, 168, 31));

        jButton3.setText("Hesabımı Kilitle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 227, 270, 41));
        getContentPane().add(asss, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 84, 167, -1));
        getContentPane().add(saaaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 115, 167, -1));
        getContentPane().add(kkkk, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 146, 167, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
/* Altta yer alan komutlarda Ara bellek sınıfından kullanıcı hangi kimlik numarası ile giriş yapmış ise o kimlik numarasından 
        o bilgiyi çekmesini istedim Ve o bilgi üzerinden işlemler yaptım. Conecttion ile bağlantıları 
        oluşturup Veri tabanına gerekli işlemlerini kaydetmesini sağladım ve buna ilaven sunucuya bilgi göndermesini istedim.
        Bu bilgi sayesinde sunucun gerekli iletimi sağlamasını sağladım.*/

String kimlikNumarasi=araBellek.musteriNumarasi; 
try{
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/projeveritabani","root","");
      Statement std=(Statement) con.createStatement();
      String kAdi=String.valueOf(kimlikNumarasi);
      System.out.println("Buraya Kadar sorunsuz çalıştı 2");
      String SQL ="SELECT * FROM musterikayit WHERE musteriKimlikNo='"+kAdi+"'";
      ResultSet rs =std.executeQuery(SQL);
      System.out.println("Buraya Kadar sorunsuz çalıştı 3");
      while(rs.next()){
          cikisNesne.writeObject("HesapBilgiGetir");
          cikisNesne.writeObject("Kullanıcı Hesap Kilitlemede Bilgileri getirdi.");
         asss.setText(""+rs.getString("musteriAdi"));
         saaaa.setText(""+rs.getString("musteriSoyadi"));
         kkkk.setText(""+rs.getString("musteriKimlikNo"));
        
        
      
      }
      
      
      
      }catch(Exception e){}








        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
/* Allta yer alan komutlar ile geri butonuna basıldığında hem anasayfa dönmesini hemde sunucuya bilgilendirme nesnesini 
        yollamasını sağladım.*/
        try{    
        KullanıcıAnaSayfa scxv=new KullanıcıAnaSayfa();
        scxv.yukle(socket, cikisNesne, girisNesne);
        scxv.setVisible(true);
        this.setVisible(false);
     
        cikisNesne.writeObject("hesapkitlemegeri");
        cikisNesne.writeObject("Kullanıcı Hesap Kilitlemeden Ana Sayfaya Geri Döndü.");
    
}catch(Exception ex){
    
   
}
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
/*Alta yer alan kodlarda 3 string tipinde nesne üretip o nesnelere textfield'larda yer alan değişkenleri atadım.
        Ve buna ilaven veritabanına bağlanarak o veritabanına geri bildirim sağlayarak hesabın kilitlenmesini sağladım 
        Bu işlemi 1 olan değeri 0'a döndürerek sağladım.*/

        String adinizaa = String.valueOf(asss.getText());
        String soyadinizaa=String.valueOf(saaaa.getText());
        String kimlikNumaaa=String.valueOf(kkkk.getText());
       
       
       
       
         
        try 
        { 
            Class.forName("com.mysql.jdbc.Driver");
            
            /*Değişkenleri tanımladık*/
            String baglantiYolu="jdbc:mysql://localhost:3306/projeveritabani";
            String kullaniciAdi="root";
            String parola="";
            cikisNesne.writeObject("hesapkilitlemebtn");
            cikisNesne.writeObject("Kullanıcı Hesabını Kilitledi.");
            System.out.println("Buraya Kadar sorunsuz çalıştı 1");
            /* Bağlantı nesnesi oluşturuldu*/
            Connection bn=DriverManager.getConnection(baglantiYolu,kullaniciAdi,parola);
        
             
            
        
           System.out.println("Buraya Kadar sorunsuz çalıştı 2");
          
            String sorgu="INSERT INTO hesapkilitleme(HesapMusteriAdi,HesaMusteriSoyadi,HesapMusteriKimlik,HesapDurumu) VALUES(?,?,?,?)";
            PreparedStatement   PreparedStatementNesnesi=bn.prepareStatement(sorgu);
            PreparedStatementNesnesi.setString(1, adinizaa);
            PreparedStatementNesnesi.setString(2, soyadinizaa);
            PreparedStatementNesnesi.setString(3, kimlikNumaaa);
            PreparedStatementNesnesi.setString(4, "1");
            System.out.println("Buraya Kadar sorunsuz çalıştı 3");
            
            int islemSonucu=PreparedStatementNesnesi.executeUpdate();
            System.out.println("Buraya Kadar sorunsuz çalıştı 4");
            if(islemSonucu>0)
            {
                JOptionPane.showMessageDialog(null, "Hesabınız Başarılı bir şekilde kilitlenmiştir.\n Hesabınızı açtırmak için Müşteri Hizmetleri ile Görüşünüz\n\n @ErdalBank Güvenli bankacılık Hizmetleri. ERDALDANİS.COM");
               asss.setText(" ");
            saaaa.setText(" ");
             kkkk.setText(" ");
          
                
                
            }else
            {
                 JOptionPane.showMessageDialog(null, "Lütfen TC ve Hesap Numarası ve Hesap Parolasını boş bırakmayınız.");
            }
           
            
        }
        catch (Exception e)
        {    
              JOptionPane.showMessageDialog(null, "Daha önceden bu kimlik numarasına ait kayıt gönderilmiştir.");
        }
            
  












        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HesapKilitlemeTalebi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HesapKilitlemeTalebi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HesapKilitlemeTalebi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HesapKilitlemeTalebi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HesapKilitlemeTalebi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asss;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField kkkk;
    private javax.swing.JTextField saaaa;
    // End of variables declaration//GEN-END:variables
}
