/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ErdalBankKullanıcıPaneli;

import ErdalBankYoneticiPaneli.araBellek;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class KullaniciCariHesapCek extends javax.swing.JFrame {
 Socket socket;
          ObjectOutputStream cikisNesne;
          ObjectInputStream girisNesne;
    /**
     * Creates new form KullaniciCariHesapCek
     */
    public KullaniciCariHesapCek() {
        initComponents();
    }
public void yukle(Socket socket, ObjectOutputStream cikisNesne,ObjectInputStream girisNesne){
        this.socket=socket;
        this.cikisNesne=cikisNesne;
        this.girisNesne=girisNesne;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        asa = new javax.swing.JTextField();
        sas = new javax.swing.JTextField();
        hsp = new javax.swing.JTextField();
        cek = new javax.swing.JTextField();
        çk = new javax.swing.JTextField();
        yt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ERDAL BANK CARİ HESAP BORÇ/SENET İŞLEMLERİ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Adınız :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Soyadınız :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hesap Numaranız :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Hesap Bilgileri :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Çekilecek Tutar :");

        jButton1.setText("Getir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Geri Dön");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Borç Senet Al");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(asa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(sas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(hsp, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(cek, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(çk, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(yt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(asa)
                            .addComponent(sas)
                            .addComponent(hsp)
                            .addComponent(cek))))
                .addContainerGap(50, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addComponent(yt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(çk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(asa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(hsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(çk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            String kimlikNumarasi=araBellek.musteriNumarasi; 
            String para=String.valueOf(cek.getText());
            int fark;
            int x,y;
           
        try 
        { 
            Class.forName("com.mysql.jdbc.Driver");
        
            /*Değişkenleri tanımladık*/
            String baglantiYolu="jdbc:mysql://localhost:3306/projeveritabani";
            String kullaniciAdi="root";
            String parola="";
            
            System.out.println("Buraya Kadar sorunsuz çalıştı 1");
            /* Bağlantı nesnesi oluşturuldu*/
            Connection bn=DriverManager.getConnection(baglantiYolu,kullaniciAdi,parola);

        
            System.out.println("Buraya Kadar sorunsuz çalıştı 2");
           
            
             Statement std=(Statement) bn.createStatement();
            String kAdi=String.valueOf(kimlikNumarasi);
             String SQL ="SELECT * FROM carihesaptablosu WHERE cariHesapKimlikNumara='"+kAdi+"'";
             ResultSet rs =std.executeQuery(SQL);
                
                while(rs.next()){
            
                 yt.setText(""+rs.getString("cariHesapBakiye"));
                 
                 }
                
                /*Yukarıda yer alan bilgilendirmede veritabanına bağlanıp o veritabanı üzerinde işlemler yaptım.
                Aynı şekilde en üstte yer alan arabellek sınıfından nesne üretip o tc numarasına ait bilgilendirmeyi
                yaptım. O tc numarasına ait bilgilendirme üzerinden o numaraya bilgiler yazdırdım.
                Alt tarafta yer alan nesneler getText ve setText'lerde Para yatırma işlemini gerçekleştirdim.
                Ve bunlara ilaven sunucuya bilgilendirme gönderdim. Ve bu bilgilendirme de farklı olarak sayı2 nesnesini
                gönderdim. O nesneden kaç tl yatırılacağına dair bilgilendirme aldım.*/
            
                String sayi1=yt.getText();
                String sayi2=cek.getText();
                cikisNesne.writeObject("carihesapparacekmebutonununici");
                cikisNesne.writeObject(sayi2);
                sayi1=yt.getText();
                sayi2=cek.getText();
                x=Integer.parseInt(sayi1);
                y=Integer.parseInt(sayi2);
                fark=x-y;
                System.out.println(fark);
                çk.setText(""+fark);
            
            
            
          
            String guncellemeSorgusu="UPDATE  carihesaptablosu set "
                                        + "cariHesapBakiye=?"
                                        + " WHERE cariHesapKimlikNumara=?"; 
            
            
            PreparedStatement   PreparedStatementNesnesi=bn.prepareStatement(guncellemeSorgusu);
            PreparedStatementNesnesi.setString(1, String.valueOf(çk.getText()));
            PreparedStatementNesnesi.setString(2, kimlikNumarasi);
            
            
            
            
            
           
            System.out.println("Buraya Kadar sorunsuz çalıştı 3");
            
            int islemSonucu=PreparedStatementNesnesi.executeUpdate();
            System.out.println("Buraya Kadar sorunsuz çalıştı 4");
            if(islemSonucu>0)
            {
                JOptionPane.showMessageDialog(null, "Para Hesabınızdan Çekilmiştir. @ErdalBank Güvencesiyle: erdaldanis.com");
                
            }else
            {
                 JOptionPane.showMessageDialog(null, "Lütfen Cekeceğiniz Tutarı Giriniz");
            }
           
            
        }
        catch (Exception e)
        {    
              JOptionPane.showMessageDialog(null, "HATA Verdi.");
        }     
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /*Altta yer alan bilgilerde ilk önce oluşturmuş olduğum arabellek sınıfından müşteri numarasını çektim.
        Connection bağlantısı kullarak nesne ile veritabanına bağlandım.
        SQL bağlantısındaki verileri bir döngüye sokarak bu döngü içerisinde 
        sunucuya bir bilgilendirme nesnesini ürettim. Ve sunucuda bu bilgilendirme nesnesinden çıktıları verdirdim. 
        Veri tabanından her bigiyi içeriye çektim. Bu bilgileri text field'lardaki uygun
        yerlere gönderdim.*/

String kimlikNumarasi=araBellek.musteriNumarasi; 
try{
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/projeveritabani","root","");
      Statement std=(Statement) con.createStatement();
      String kAdi=String.valueOf(kimlikNumarasi);
      System.out.println("Buraya Kadar sorunsuz çalıştı 2");
      String SQL ="SELECT * FROM carihesaptablosu WHERE cariHesapKimlikNumara='"+kAdi+"'";
      ResultSet rs =std.executeQuery(SQL);
      System.out.println("Buraya Kadar sorunsuz çalıştı 3");
      while(rs.next()){
          
          cikisNesne.writeObject("carihesapparacekmebilgi");
          cikisNesne.writeObject("Kullanıcı Cari Hesaptan Para Çekme Bilgileri Görüntüledi.");
          
         asa.setText(""+rs.getString("cariHesapMusteriAdi"));
         sas.setText(""+rs.getString("cariHesapMusteriSoyadi"));
         hsp.setText(""+rs.getString("cariHesapMusteriHesapNo"));
        
        
      
      }
      
      
      
      }catch(Exception e){}









        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{KullanıcıAnaSayfa sad=new KullanıcıAnaSayfa();
sad.yukle(socket, cikisNesne, girisNesne);
sad.setVisible(true);
this.setVisible(false);
/*Altta ve yukarıda yer alan bilgilerde try catch komutlarına soktuğum nesnelerde geri tuşuna 
basılırken bu işlemlerin çalışmasını anasayfaya dönüülmesini sağladım. Bununla birlikte 
Sunucuya 2 nesne üretip birincisi ile if koşullarını belirtip ikincisinde o çıktıyı verdirdim.
*/
cikisNesne.writeObject("cariHesapParacekmegeri");
cikisNesne.writeObject("Kullanıcı Cari Para Çekme'den Anasayfa'ya gitti.");
}catch(Exception ex){
    
    
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciCariHesapCek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciCariHesapCek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciCariHesapCek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciCariHesapCek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciCariHesapCek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asa;
    private javax.swing.JTextField cek;
    private javax.swing.JTextField hsp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField sas;
    private javax.swing.JTextField yt;
    private javax.swing.JTextField çk;
    // End of variables declaration//GEN-END:variables
}
