/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ErdalBankKullanıcıPaneli;

import ErdalBankYoneticiPaneli.araBellek;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class KullanıcıAnaSayfa extends javax.swing.JFrame {

    /**
     * Creates new form KullanıcıAnaSayfa
     */
    Socket socket;
          ObjectOutputStream cikisNesne;
          ObjectInputStream girisNesne;
    public KullanıcıAnaSayfa() {
         
        
        
        initComponents();
        
        
        
     
        
        
    }
    public void yukle(Socket socket, ObjectOutputStream cikisNesne,ObjectInputStream girisNesne){
        this.socket=socket;
        this.cikisNesne=cikisNesne;
        this.girisNesne=girisNesne;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        jMenu4.setText("jMenu4");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jDesktopPane1MouseReleased(evt);
            }
        });
        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setText("Kısa Vadeli Hesap Görüntüle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 220, 31));

        jButton9.setBackground(new java.awt.Color(255, 51, 51));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Vadesiz Hesaba Para Yatırma");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 200, 31));

        jButton7.setBackground(new java.awt.Color(255, 51, 51));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Vadesiz Hesap Görüntüle");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 440, 31));

        jButton10.setBackground(new java.awt.Color(255, 51, 51));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Vadesiz Hesaptan Para Çekme");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 230, 31));

        jButton8.setBackground(new java.awt.Color(0, 255, 0));
        jButton8.setText("Cari Hesap Görüntüle");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 440, 31));

        jButton11.setBackground(new java.awt.Color(102, 102, 0));
        jButton11.setText("Çıkış Yap");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 440, 31));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ERDAL BANK KULLANICI İŞLEMLERİ");
        jDesktopPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("KİŞİSEL SAYFA PANELİNE HOŞ GELDİNİZ");
        jDesktopPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setText("Kısa Vadeli Hesap Para Yatırma");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 220, 32));

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setText("Kısa Vadeli Hesap Para Çekme");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 220, 32));

        jButton14.setBackground(new java.awt.Color(255, 204, 0));
        jButton14.setText("Borç/Senet Çek");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 201, 31));

        jButton15.setBackground(new java.awt.Color(255, 153, 0));
        jButton15.setText("Borç/Senet Öde");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 230, 31));

        jButton18.setBackground(new java.awt.Color(153, 153, 255));
        jButton18.setText("Uzun Vadeli Hesap Görüntüle");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton18MouseReleased(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 210, 30));

        jButton19.setBackground(new java.awt.Color(153, 153, 255));
        jButton19.setText("Uzun Vadeli Hesap Para Yatırma");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 210, 30));

        jButton20.setBackground(new java.awt.Color(153, 153, 255));
        jButton20.setText("Uzun Vadeli Hesap Para Çekme");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 210, 30));

        jButton1.setText("Hesabımı Kilitle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 440, 30));

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
                               
                      KullanıcıKısaVadeliHesapGörüntüleme asa=new KullanıcıKısaVadeliHesapGörüntüleme();
                     asa.yukle(socket, cikisNesne, girisNesne);
                      asa.setVisible(true);
                    this.setVisible(false);
                        
                         cikisNesne.writeObject("kisavade");
                         cikisNesne.writeObject("Kullanıcı Kısa Vadeli Hesap'a Başarili Bir Şekilde Giriş Yaptı.");
                        
                         
                  
                             } catch (IOException ex) {
                            Logger.getLogger(KullanıcıGirisPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }
                                
       
         
       

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
             KullanıcıVadesizHesapGoruntule gorNesne=new KullanıcıVadesizHesapGoruntule();
             gorNesne.yukle(socket, cikisNesne, girisNesne);
             gorNesne.setVisible(true);
             this.setVisible(false);          
           
             cikisNesne.writeObject("vadesiz");
             cikisNesne.writeObject("Kullanıcı Vadesiz Hesap Görüntülüye  Başarili Bir Şekilde Giriş Yaptı");
                        
            } catch (IOException ex) {
                            Logger.getLogger(KullanıcıGirisPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }    
        
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
try{
    KullanıcıCariHesapGörüntüleme asd=new KullanıcıCariHesapGörüntüleme();
       asd.yukle(socket, cikisNesne, girisNesne);
    asd.setVisible(true);
    this.setVisible(false);
    
    cikisNesne.writeObject("CariHesapGoruntule");
    cikisNesne.writeObject("Kullanıcı Cari Hesabı Görüntüledi");
}catch(Exception ex){
    
}
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
try{
    
    dispose();
    cikisNesne.writeObject("cikisyap");
    cikisNesne.writeObject("Kullanıcı Hesabından Çıkış Yaptı.\n Sunucu Ve Port Kapatıldı.");
    
}catch(Exception ex){
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
 try {
           KullanıcıParaYatırma nesnee = new KullanıcıParaYatırma();
            nesnee.yukle(socket, cikisNesne, girisNesne);
             nesnee.setVisible(true);
            this.setVisible(false);

           
             cikisNesne.writeObject("vadesizparayatirbutonana");
             cikisNesne.writeObject("Kullanıcı Vadesiz Para Yatırma Hesabına giriş yaptı.");
                        
            } catch (IOException ex) {
                            Logger.getLogger(KullanıcıGirisPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }    
           
       
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      try {
          KullanıcıParaÇekme Çnesnee = new KullanıcıParaÇekme();
            Çnesnee.yukle(socket, cikisNesne, girisNesne);
             Çnesnee.setVisible(true);
            this.setVisible(false);

           
             cikisNesne.writeObject("vadesizparacekbuton");
             cikisNesne.writeObject("Kullanıcı Vadesiz Para Cekme Hesabına giriş yaptı.");
                        
            } catch (IOException ex) {
                            Logger.getLogger(KullanıcıGirisPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }    
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
 try {
             KullaniciUzunVadeliHesapGoruntule UT=new KullaniciUzunVadeliHesapGoruntule();
            UT.yukle(socket, cikisNesne, girisNesne);
             UT.setVisible(true);
            this.setVisible(false);

           
             cikisNesne.writeObject("uzunVadeliparayatirb");
             cikisNesne.writeObject("Kullanıcı Uzun Vadeli Para Yatırma Hesabına giriş yaptı.");
                        
            } catch (IOException ex) {
                            Logger.getLogger(KullanıcıGirisPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }    
           
            
           
             


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
   try {
                               
              KullanıcıUzunVadeliParaYatırma uyt=new KullanıcıUzunVadeliParaYatırma();
              uyt.yukle(socket, cikisNesne, girisNesne);
              uyt.setVisible(true);
              this.setVisible(false);
              cikisNesne.writeObject("uzunvadeparaYatir");
              cikisNesne.writeObject("Kullanıcı Uzun Vadeli Para Yatırmaya Başarili Bir Şekilde Giriş Yaptı.");
                        
                         
                  
                             } catch (IOException ex) {
                            Logger.getLogger(KullanıcıGirisPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }
       
   
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
 try {
                               
             KullanıcıUzunVadeliParaCekme uytu=new KullanıcıUzunVadeliParaCekme();
              uytu.yukle(socket, cikisNesne, girisNesne);
              uytu.setVisible(true);
              this.setVisible(false);
              cikisNesne.writeObject("uzunvadeparaCek");
              cikisNesne.writeObject("Kullanıcı Uzun Vadeli Para Cekmeye Başarili Bir Şekilde Giriş Yaptı.");
                        
                         
                  
                             } catch (IOException ex) {
                            Logger.getLogger(KullanıcıGirisPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }
       


       // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
                               
              KullanıcıKısaVadeliParaYatırma aaaNesnesi=new KullanıcıKısaVadeliParaYatırma();
              aaaNesnesi.yukle(socket, cikisNesne, girisNesne);
              aaaNesnesi.setVisible(true);
              this.setVisible(false);
              cikisNesne.writeObject("kisavadeparaYatir");
              cikisNesne.writeObject("Kullanıcı Kısa Vadeli Para Yatırmaya Başarili Bir Şekilde Giriş Yaptı.");
                        
                         
                  
                             } catch (IOException ex) {
                            Logger.getLogger(KullanıcıGirisPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }
        
        


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 try {
                               
              KullanıcıKısaVadeliParaCekme asadsasd=new KullanıcıKısaVadeliParaCekme();
              asadsasd.yukle(socket, cikisNesne, girisNesne);
              asadsasd.setVisible(true);
              this.setVisible(false);
              cikisNesne.writeObject("kisavadeparacek");
              cikisNesne.writeObject("Kullanıcı Kısa Vadeli Para Cekmeye başarili Bir Şekilde Giriş Yaptı.");
                        
                         
                  
                             } catch (IOException ex) {
                            Logger.getLogger(KullanıcıGirisPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }
        
        
        
       
           
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
    HesapKilitlemeTalebi sad=new HesapKilitlemeTalebi();
    sad.yukle(socket, cikisNesne, girisNesne);
    sad.setVisible(true);
    this.setVisible(false);
    
    cikisNesne.writeObject("hesapkilitlebtn");
    cikisNesne.writeObject("Kullanıcı Hesap Kilitleme İşlemlerine Giriş Yaptı.");
}catch(Exception ex){
    
    
}
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDesktopPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDesktopPane1MouseReleased
 String kimlikNumarasi=araBellek.musteriNumarasi; 
        try
        {
            Class.forName("com.mysql.jdbc.Driver");

            String baglantiYolu="jdbc:mysql://localhost:3306/projeveritabani";
            String kullaniciAdi="root";
            String parola="";

            Connection baglantiNesnesi=DriverManager.getConnection(baglantiYolu,kullaniciAdi,parola);
            String sorgu="SELECT*FROM hesapkilitleme";

            Statement statementNesnesi=baglantiNesnesi.createStatement();

            ResultSet rsNesnesi=(ResultSet)statementNesnesi.executeQuery(sorgu);

            int sayac=0;
            while (rsNesnesi.next())
            {
                if(rsNesnesi.getString("HesapMusteriKimlik").equals(kimlikNumarasi))
                {
                    if(rsNesnesi.getString("HesapDurumu").equals("1"))
                    {
                        
                    JOptionPane.showMessageDialog(null, "Hesabınız Kilitlidir.");
                        KullanıcıGirisPaneli SA=new KullanıcıGirisPaneli();
                        SA.setVisible(true);
                        this.setVisible(false);
                               
                        
                        
                        
                    }else
                    {
                        
                    }

                }

            }
        } catch (Exception e)
        {

            JOptionPane.showMessageDialog(null, "Giriş Yapılamadı ! ");

        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jDesktopPane1MouseReleased

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
try{
 KullaniciCariHesapCek asd=new KullaniciCariHesapCek();
asd.yukle(socket, cikisNesne, girisNesne);
asd.setVisible(true);
this.setVisible(false);
cikisNesne.writeObject("CariHesapParaCek");
cikisNesne.writeObject("Kullanıcı Cari Hesabtan Para Çekme İşlemlerini Görüntüledi.");
    
}catch(Exception ex){
    
    
}
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
   try{
    KullaniciCariHesapYatir sd=new KullaniciCariHesapYatir();
    sd.yukle(socket, cikisNesne, girisNesne);
    sd.setVisible(true);
    this.setVisible(false);
    
    cikisNesne.writeObject("CariHesapParaYatir");
    cikisNesne.writeObject("Kullanıcı Cari Hesap Para Yatırma İşlemlerine Giriş Yapıldı.");
       
   }catch(Exception ex){
       
   }
        
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton18MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullanıcıAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullanıcıAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullanıcıAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullanıcıAnaSayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullanıcıAnaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    // End of variables declaration//GEN-END:variables

    private void cikisNesne(String cas) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
