/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ErdalBankKullanıcıPaneli;

import ErdalBankYoneticiPaneli.araBellek;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class KullanıcıKısaVadeliHesapGörüntüleme extends javax.swing.JFrame {
            Socket socket;
          ObjectOutputStream cikisNesne;
          ObjectInputStream girisNesne;
    /** Creates new form KullanıcıKısaVadeliHesapGörüntüleme */
    public KullanıcıKısaVadeliHesapGörüntüleme() {
        initComponents();
    }
    
    
     public void yukle(Socket socket, ObjectOutputStream cikisNesne,ObjectInputStream girisNesne){
        this.socket=socket;
        this.cikisNesne=cikisNesne;
        this.girisNesne=girisNesne;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kisaHesapNo = new javax.swing.JTextField();
        kisaHesapBakiye = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kisaHesapOran = new javax.swing.JTextField();
        kisaHesapOranBakiye = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        ss = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("ERDAL BANK KISA VADELİ HESAP GÖRÜNTÜLEME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, -1, 39));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hesap Numaranız :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hesap Bakiyeniz :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 120, 30));
        getContentPane().add(kisaHesapNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 72, 187, -1));

        kisaHesapBakiye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kisaHesapBakiyeActionPerformed(evt);
            }
        });
        getContentPane().add(kisaHesapBakiye, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 103, 187, -1));

        jButton1.setText("Geri");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 133, 120, 32));

        jButton2.setText("Hesabımı Görüntüle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 133, 187, 32));

        jButton3.setText("Faiz Oranı Ve Yeni Bakiye");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 171, 313, 34));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Oran :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 216, -1, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Oran*Bakiye :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 252, -1, 30));
        getContentPane().add(kisaHesapOran, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 222, 224, -1));

        kisaHesapOranBakiye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kisaHesapOranBakiyeActionPerformed(evt);
            }
        });
        getContentPane().add(kisaHesapOranBakiye, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 258, 225, -1));

        jDesktopPane1.setLayer(ss, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 394, Short.MAX_VALUE)
                .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 312, Short.MAX_VALUE)
                .addComponent(ss, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kisaHesapBakiyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kisaHesapBakiyeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kisaHesapBakiyeActionPerformed

    private void kisaHesapOranBakiyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kisaHesapOranBakiyeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kisaHesapOranBakiyeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try {
                               
     KullanıcıAnaSayfa ASD=new KullanıcıAnaSayfa();
     ASD.yukle(socket, cikisNesne, girisNesne);
    ASD.setVisible(true);
    this.setVisible(false);
                        
    cikisNesne.writeObject("kisavadeliic");
    cikisNesne.writeObject("Kullanıcı Kısa Vadeli Hesaptan Anasayfa'ya Gitti");
                        
                         
                  
                             } catch (IOException ex) {
                            Logger.getLogger(KullanıcıGirisPaneli.class.getName()).log(Level.SEVERE, null, ex);
                    }
        
        
        
        
  // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

            String kimlikNumarasi=araBellek.musteriNumarasi;
            System.out.println(kimlikNumarasi);

  try{
      cikisNesne.writeObject("kisavadeGorunt");
      cikisNesne.writeObject("Kullanıcı Kısa Vadeli Hesabını Görüntüledi.");
      
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/projeveritabani","root","");
      Statement std=(Statement) con.createStatement();
      String kAdi=String.valueOf(kimlikNumarasi);
      System.out.println("Buraya Kadar sorunsuz çalıştı 2");
      String SQL ="SELECT * FROM kisavadelihesapkayit WHERE kisaVadeliMusteriTcNo='"+kAdi+"'";
      ResultSet rs =std.executeQuery(SQL);
      System.out.println("Buraya Kadar sorunsuz çalıştı 3");
      while(rs.next()){
          
          kisaHesapNo.setText(""+rs.getString("kisaVadeliMusteriHesapNo"));
         kisaHesapBakiye.setText(""+rs.getString("kisaVadeliMusteriBakiye"));
        
         
      
      }System.out.println("Buraya Kadar sorunsuz çalıştı 3");
      
        
      
      }catch(Exception e){}







        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed


            String kimlikNumarasi=araBellek.musteriNumarasi; 
            String para=String.valueOf(kisaHesapBakiye.getText());
            int carpim,bolum,toplam;
            float bakiye;
            int x,y;
           
        try 
        {  
            Class.forName("com.mysql.jdbc.Driver");
        
            /*Değişkenleri tanımladık*/
            String baglantiYolu="jdbc:mysql://localhost:3306/projeveritabani";
            String kullaniciAdi="root";
            String parola="";
            
            System.out.println("Buraya Kadar sorunsuz çalıştı 1");
            /* Bağlantı nesnesi oluşturuldu*/
            
            
            Connection bn=DriverManager.getConnection(baglantiYolu,kullaniciAdi,parola);

        
            System.out.println("Buraya Kadar sorunsuz çalıştı 2");
           
            
             Statement std=(Statement) bn.createStatement();
             String kAdi=String.valueOf(kimlikNumarasi);
             
             String SQL ="SELECT * FROM kisavadelihesapkayit WHERE kisaVadeliMusteriTcNo='"+kAdi+"'";
             
             System.out.println("Buraya Kadar sorunsuz çalıştı 3");
             ResultSet rs =std.executeQuery(SQL);
                
                while(rs.next()){
             cikisNesne.writeObject("kisavadefaiz");
            cikisNesne.writeObject("Kullanıcı Kısa Vadeli Hesabını Faiz Oranını Görüntüledi.");
                 ss.setText(""+rs.getString("kisaVadeliMusteriBakiye"));
                 
                 }
            
                String sayi1=ss.getText();
                
                sayi1=ss.getText();
                
                x=Integer.parseInt(sayi1);
                y=8;
                carpim=x*y;
                bakiye=carpim/100;
                toplam=(int) (bakiye+x);
                System.out.println(carpim);
                kisaHesapOran.setText(""+bakiye);
                kisaHesapOranBakiye.setText(""+toplam);
            
          
          
            if(true)
            {
                JOptionPane.showMessageDialog(null, "Veriler Güncellenmiştir. @ErdalBank Güvencesiyle: erdaldanis.com");
                
            }else
            {
                 JOptionPane.showMessageDialog(null, "Veri Güncellenemedi.");
            }
           
            
        }
        catch (Exception e)
        {    
              JOptionPane.showMessageDialog(null, "Sistemi başlatın");
        }     











        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullanıcıKısaVadeliHesapGörüntüleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullanıcıKısaVadeliHesapGörüntüleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullanıcıKısaVadeliHesapGörüntüleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullanıcıKısaVadeliHesapGörüntüleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullanıcıKısaVadeliHesapGörüntüleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField kisaHesapBakiye;
    private javax.swing.JTextField kisaHesapNo;
    private javax.swing.JTextField kisaHesapOran;
    private javax.swing.JTextField kisaHesapOranBakiye;
    private javax.swing.JTextField ss;
    // End of variables declaration//GEN-END:variables

}
